SELECT C.COMPANY_CODE,
    C.FOUNDER,
    COUNT(DISTINCT L.LEAD_MANAGER_CODE),
    COUNT(DISTINCT S.SENIOR_MANAGER_CODE),
    COUNT(DISTINCT M.MANAGER_CODE),
    COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY AS C
    JOIN LEAD_MANAGER AS L ON C.COMPANY_CODE = L.COMPANY_CODE
    JOIN SENIOR_MANAGER AS S ON L.lead_manager_code = S.lead_manager_code
    JOIN Manager AS M ON S.senior_manager_code = M.senior_manager_code
    JOIN EMPLOYEE AS E ON M.manager_code = E.manager_code
Group by C.COMPANY_CODE,
    C.FOUNDER
Order by C.COMPANY_CODE;